### ISSUE TITLE
[Bug] 发送消息时发生警告

### ISSUE THREAD

**Issue by Fox-ace** [ArcletProject/Entari#9]
## 请确认：

* [ x ] 问题的标题明确
* [ x ] 我翻阅过其他的issue并且找不到类似的问题
* [ x ] 我已经阅读了[相关文档](https://satori.chat/zh-CN/) 并仍然认为这是一个Bug

# Bug

## 问题
使用`await session.send("xxx")`发送消息时控制台出现traceback，消息正常发送，但控制台出现日志

## 如何复现
使用`await session.send("xxx")`发送消息

## 预期行为
控制台应当不存在报错日志

## 使用环境:
- Python 版本: 3.12
- Entari 版本: 0.7.0

## 日志/截图
`Traceback (most recent call last):
  File "/run/media/fox/文档/AAAA-WorkFiles/Candy_Xt/Nevo-Project/lib/python3.12/site-pac
kages/arclet/letoderea/handler.py", line 126, in depend_handler
    result = await _target.callable_target(**arguments)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/fox/文档/AAAA-WorkFiles/Candy_Xt/Nevo-Project/NevoBot/main.py", line
54, in server_command
    await session.send(result)
  File "/run/media/fox/文档/AAAA-WorkFiles/Candy_Xt/Nevo-Project/lib/python3.12/site-pac
kages/arclet/entari/session.py", line 118, in send
    return await self.account.protocol.send(self.context, message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                        File "/run/media/fox/文档/AAAA-WorkFiles/Candy_Xt/Nevo-Project/lib/python3.12/site-pac
kages/satori/client/protocol.py", line 97, in send
    return await self.send_message(event.channel.id, message)                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/fox/文档/AAAA-WorkFiles/Candy_Xt/Nevo-Project/lib/python3.12/site-packages/satori/client/protocol.py", line 113, in send_message
    return await self.message_create(channel_id=channel_id, content=msg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/fox/文档/AAAA-WorkFiles/Candy_Xt/Nevo-Project/lib/python3.12/site-pac
kages/satori/client/protocol.py", line 167, in message_create
    return [MessageObject.parse(i) for i in res]                                                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/fox/文档/AAAA-WorkFiles/Candy_Xt/Nevo-Project/lib/python3.12/site-pac
kages/satori/model.py", line 268, in parse                                                  return super().parse(raw)
           ^^^^^^^^^^^^^^^^^^
  File "/run/media/fox/文档/AAAA-WorkFiles/Candy_Xt/Nevo-Project/lib/python3.12/site-packages/satori/model.py", line 29, in parse
    return cls(**data)  # type: ignore                                                             ^^^^^^^^^^^
TypeError: MessageObject.__init__() missing 1 required positional argument: 'content'
log`

**Comment by RF-Tar-Railt** [comment]
对接的协议端是什么

**Comment by Fox-ace** [comment]
> 对接的协议端是什么
Koishi Onebot

**Comment by RF-Tar-Railt** [comment]
> > 对接的协议端是什么
> 
> Koishi Onebot

请给出 koishi 的相关版本

**Comment by Fox-ace** [comment]
> > > 对接的协议端是什么
> > 
> > 
> > Koishi Onebot
> 
> 请给出 koishi 的相关版本

Koishi: v4.18.0
adapter-onebot: 6.7.2
LLOnebot: 4.0.11
LiteLoader: 1.2.2
QQNT: 3.2.12-28418
Electron: 31.0.1
Chromium: 126.0.6478.36
Node.js: 20.14.0

**Comment by RF-Tar-Railt** [comment]
初步来说是koishi-adapter-onebot的问题，我先问问 Shigma本人

**Comment by RF-Tar-Railt** [comment]
升级 0.8.0 试试
